#tenants:
#    tenant_id:
#        - <tenant_id1>
#        - <tenant_id2>
#instances:
#    id:
#        - <server_id1>
#        - <server_id2>
#images:
#    images_list:
#        - <image_id1>
#        - <image_id2>
